#!/usr/bin/env python3
import datetime
import sys

# ==============================================================================
# CONFIGURATIE
# ==============================================================================

HEADER_GUARD = "SYSCALLS_H"

# ==============================================================================
# TEMPLATES (Raw strings r"""...""" zijn nodig voor backslashes in assembly)
# ==============================================================================

HEADER = f"""#ifndef {HEADER_GUARD}
#define {HEADER_GUARD}

#include "unistd.h"

/* ============================================================
 * X86_64 SYSCALL MACROS
 * Generated by make_syscalls.py on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 *
 * Features:
 * - PIE Safe (Position Independent Executable) compatible
 * - Auto-optimization (SKIPs unused args, ignores self-moves)
 * - Zero-cost abstraction
 * ============================================================ */
"""

MACROS = r"""
/* ============================================================
 * Helper: _set_arg reg, arg
 *
 * Logic:
 * 1. SKIP       -> Do nothing (argument missing/default)
 * 2. 0          -> XOR (faster/smaller than mov $0)
 * 3. arg == reg -> Do nothing (prevents redundant mov %rsi, %rsi)
 * 4. Otherwise  -> MOV
 * ============================================================ */
.macro _set_arg reg, arg
    .ifc \arg, SKIP
        /* Do nothing (argument not provided) */
    .else
        .ifc \arg, 0
            xor \reg, \reg
        .else
            .ifnc \arg, \reg
                mov \arg, \reg
            .endif
        .endif
    .endif
.endm

/* ============================================================
 * Main Macro: _syscall
 *
 * Usage: _syscall name, arg1, arg2, ...
 * Example: _syscall write, $STDOUT, %rsi, $len
 *
 * Note: Registers not specified are defaulted to SKIP and
 * will be left untouched.
 * ============================================================ */
.macro _syscall nr, a0=SKIP, a1=SKIP, a2=SKIP, a3=SKIP, a4=SKIP, a5=SKIP
    /* Load syscall number (concatenates __NR_ + name) */
    mov $__NR_\nr, %rax

    /* Set arguments (System V AMD64 ABI) */
    /* Note: Syscalls use r10 instead of rcx for arg4! */
    _set_arg %rdi, \a0
    _set_arg %rsi, \a1
    _set_arg %rdx, \a2
    _set_arg %r10, \a3
    _set_arg %r8,  \a4
    _set_arg %r9,  \a5

    syscall
.endm
"""

FOOTER = f"""
#endif /* {HEADER_GUARD} */
"""

# ==============================================================================
# MAIN
# ==============================================================================

if __name__ == "__main__":
    # Schrijf output naar stdout
    print(HEADER)
    print(MACROS)
    print(FOOTER)
