#ifndef UNISTD_UNIFIED_H
#define UNISTD_UNIFIED_H 1

/* ============================================================
 * UNIVERSAL LINUX X86-64 SYSCALL HEADER
 * Generated by script on 2025-12-13 00:00:10
 *
 * Source: /usr/mips-linux-gnu/include/unistd.h
 *
 * Works for:
 * - GAS (.s) pure assembler  -> uses .equ
 * - C/C++ / .S preprocessed  -> uses #define
 * ============================================================ */

#if defined(__ASSEMBLER__)

/* ============================================================
 * ASSEMBLER VERSION (.equ)
 * ============================================================ */

    .ifndef UNISTD_UASM
    .set UNISTD_ASM, 1

    /* --- File Descriptors & Constants (.equ) --- */
    .equ STDIN, 0
    .equ STDOUT, 1
    .equ STDERR, 2
    .equ stdin, STDIN
    .equ stdout, STDOUT
    .equ stderr, STDERR

    /* --- Syscalls (.equ) --- */

    .endif /* UNISTD_UASM */

#else /* ============ C / C++ VERSION =============== */

#ifndef UNISTD_UNIFIED_C
#define UNISTD_UNIFIED_C 1

/* --- File Descriptors & Constants (#define) --- */
#define STDIN 0
#define STDOUT 1
#define STDERR 2
#define stdin STDIN
#define stdout STDOUT
#define stderr STDERR

/* --- Syscalls (#define) --- */

#endif /* UNISTD_UNIFIED_C */
#endif /* __ASSEMBLER__ */

#endif /* UNISTD_UNIFIED_H */

