#!/usr/bin/env python3
import sys
import re
import datetime
import os

# ==============================================================================
# CONFIGURATIE (DE "SINGLE SOURCE OF TRUTH")
# ==============================================================================

HEADER_GUARD = "UNISTD_UNIFIED_H"

# Hier definieer je je constanten 1 keer.
# Het script genereert ze automatisch voor zowel .equ als #define
CONSTANTS = {
    # Naam      : Waarde
    "STDIN"     : "0",
    "STDOUT"    : "1",
    "STDERR"    : "2",
    
    # Aliases verwijzen naar de namen hierboven
    "stdin"     : "STDIN",
    "stdout"    : "STDOUT",
    "stderr"    : "STDERR",
}

# ==============================================================================
# TEMPLATES
# ==============================================================================

def get_header_top(input_path):
    abs_path = os.path.abspath(input_path)
    return f"""#ifndef {HEADER_GUARD}
#define {HEADER_GUARD} 1

/* ============================================================
 * UNIVERSAL LINUX X86-64 SYSCALL HEADER
 * Generated by script on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 *
 * Source: {abs_path}
 *
 * Works for:
 * - GAS (.s) pure assembler  -> uses .equ
 * - C/C++ / .S preprocessed  -> uses #define
 * ============================================================ */

#if defined(__ASSEMBLER__)

/* ============================================================
 * ASSEMBLER VERSION (.equ)
 * ============================================================ */

    .ifndef UNISTD_UASM
    .set UNISTD_ASM, 1
"""

MIDDLE_SECTION = """
    .endif /* UNISTD_UASM */

#else /* ============ C / C++ VERSION =============== */

#ifndef UNISTD_UNIFIED_C
#define UNISTD_UNIFIED_C 1
"""

FOOTER = f"""
#endif /* UNISTD_UNIFIED_C */
#endif /* __ASSEMBLER__ */

#endif /* {HEADER_GUARD} */
"""

# ==============================================================================
# LOGICA
# ==============================================================================

def parse_input_file(filepath):
    syscalls = []
    regex = re.compile(r'^\s*#define\s+__NR_(\w+)\s+(\d+)')
    try:
        with open(filepath, 'r') as f:
            for line in f:
                match = regex.match(line)
                if match:
                    syscalls.append((match.group(1), match.group(2)))
    except FileNotFoundError:
        print(f"Fout: Bestand '{filepath}' niet gevonden.", file=sys.stderr)
        sys.exit(1)
    return syscalls

def generate_output(syscalls, input_path):
    # 1. Header
    print(get_header_top(input_path))

    # ---------------------------------------------------------
    # DEEL A: ASSEMBLER GENERATIE
    # ---------------------------------------------------------
    print("    /* --- File Descriptors & Constants (.equ) --- */")
    for name, value in CONSTANTS.items():
        # Format: .equ NAAM, WAARDE
        print(f"    .equ {name}, {value}")

    print("\n    /* --- Syscalls (.equ) --- */")
    for name, number in syscalls:
        print(f"    .equ __NR_{name}, {number}")

    # 2. Middenstuk
    print(MIDDLE_SECTION)

    # ---------------------------------------------------------
    # DEEL B: C/C++ GENERATIE
    # ---------------------------------------------------------
    print("/* --- File Descriptors & Constants (#define) --- */")
    for name, value in CONSTANTS.items():
        # Format: #define NAAM WAARDE (Geen komma!)
        print(f"#define {name} {value}")

    print("\n/* --- Syscalls (#define) --- */")
    for name, number in syscalls:
        print(f"#define __NR_{name} {number}")

    # 3. Footer
    print(FOOTER)

# ==============================================================================
# MAIN
# ==============================================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Gebruik: python3 make_unistd.py <pad_naar_kernel_unistd_64.h>")
        sys.exit(1)

    input_file = sys.argv[1]
    syscall_list = parse_input_file(input_file)
    generate_output(syscall_list, input_file)
